name: PixAI Auto Signin

on:
  schedule:
    # 每天 UTC 时间 2 点20运行 (北京时间 10 点20)
    - cron : '20 02 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  Signin:
    runs-on: ubuntu-latest
    steps:
      - name: Run Auto Signin
        env:
          LOGINNAME: ${{ secrets.LOGINNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker pull smile0301/auto-pixai
          docker run --rm \
            -e LOGINNAME="$LOGINNAME" \
            -e PASSWORD="$PASSWORD" \
            smile0301/auto-pixai
